---
title: |
  Pandemic Dilemmas: Human perception of exponentially increasing data displayed on a log scale evaluated through graphics experimental tasks
type:
  - JSM 2021 Contributed Abstract
author:
  - name: Emily A. Robinson
    affil: a
    email: emily.robinson@huskers.unl.edu
  - name: Reka Howard
    affil: a
  - name: Susan VanderPlas
    affil: a
affiliation:
  - num: a
    address: |
      Department of Statistics, University of Nebraska - Lincoln,
# bibliography: references.bib
output: 
  pdf_document:
    template: template-abstract.tex
    # template: template-abstract-blinded.tex
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F, eval = T, fig.path="./images/", fig.env="figure*")
```


Log scales are often used to display data over several orders of magnitude within one graph. 
During the COVID-19 pandemic, we have seen both the benefits and the pitfalls of using log scales to display case counts.
Three graphical experimental tasks were conducted to evaluate the impact our choice of scale has on human perception of exponentially increasing trends. 
The first experimental evaluates whether our ability to perceptually notice differences in exponentially increasing trends is impacted by the choice of scale. We conducted a visual inference experiment in which participants were shown a series of lineup plots (consisting of 19 null panels and 1 target panel generated by differing model parameters) and asked to identify the panel that was most different from the others.
Our results indicated that when there was a large difference in curvature between the target plot and null plots, the choice of scale had no impact and participants accurately differentiated between the two curves on both the linear and log scale. 
However, displaying exponentially increasing data on a log scale improved the accuracy of differentiating between models with slight curvature differences.
An exception occurred when identifying a plot with curvature embedded in surrounding plots closely relating to a linear trend, indicating that it is easy to identify a curve in a group of lines but much harder to identify a line in a group of curves.
The use of visual inference to identify these guidelines suggests that there are \emph{perceptual} advantages to log scales when differences are subtle.
Our other experimental tasks focus on determining whether there are cognitive disadvantages to log scales: do log scales make it harder to make use of graphical information?
We conducted a graphical task similar to the New York Times "You Draw It" page to test an individual's ability to use and make predictions for exponentially increasing data by asking participants to draw a line using their computer mouse through the increasing exponential trend shown on both scales.
In addition to differentiation and prediction of exponentially increasing data, we conduct an experimental task to test an individuals' ability to translate a graph of exponentially increasing data into real value quantities and extend their estimations by making comparisons. 
The results of our experimental tasks allow us to provide guidelines for readers to actively choose which of many possible graphics to draw, according to some set of design choices, to ensure that our charts are effective.
