---
title: "Previous Literature"
author: "Emily Robinson"
output: html_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, fig.width = 8, fig.height = 4, out.width = "100%", dpi = 300, message = F)
```

### Log vs Linear Scale

- @woloshin_new_2000 

    - measured the perceptions of event probabilities, particularly low probabilities (i.e., <1%) by comparing four scales - logaraithm pct, linear words, linear numbers, and "1 in x" - in terms of reliability and validity. The authors found that the "1 in x" scale performs poorly and is very difficult for people to use. The magnifier scale and the linear number scale are similar in validity, reliability, and usability. However, only the magnifier scale makes it possible to elicit perceptions in the low-probability range (<1%).

- @dehaeneLogLinearDistinct2008 

    - reveal both universal and culture-dependent facets of the sense of number. After a minimal instruction period, even members of a remote culture with reduced vocabulary and education readily understand that number can be mapped onto a spatial scale. The exact form of this mapping switches dramatically from logarithmic to linear, however, depending on the ages at which people are tested, the education they have received, and the format in which numbers are presented.

### You Draw It
- @mosteller_eye_1981 

    - designed and carried out an empirical investigation to explore properties of lines fitted by eye. The researchers found that students tended to fit the slope of the first principal component or major axis (the line that minimizes the sum of squares of perpendicular rather than vertical distances) and that students who gave steep slopes for one data set also tended to give steep slopes on the others. Interestingly, the individual-to-individual variability in slope and in intercept was near the standard error provided by least squares for the four data sets.

### Lineup

- @best_perception_2007

    - Compared many factors: exponential, asymptotic, and linear trends increasing or decreasing bar, suspended bar, scatter, and line plots number of points high, medium, low variability

    - Asked to identify the type of curve (exponential, asymptotic, linear; increasing, decreasing) definition of exponential decreasing is … not what a mathematician would use. y=C+−ex instead of y=e−x. y=e−x is what they’ve defined as asymptotic decreasing. n=6 with ~2k trials per participant

    - hypothesis is 2-stage estimation: first, identify the type of curve and direction, then use that information for prediction

    - this experiment is examining whether discrimination between curve types is possible
    - Results:
        - accuracy higher when nonlinear trends presented (e.g. it’s hard to say something is linear, but easy to say that it isn’t)
        - accuracy higher with low variability – variability was additive, e.g. constant variance around mean function it appears that participants examined curvature to make the determination of type

### Estimation
-  @friel_making_2001 

    - emphasize the importance of graph comprehension proposing that the graph construction plays a role in the ability to read and interpret graphs.

### Growth Rate

- @wagenaar_misperception_1975, 

    - Perceptual issue: ability to discriminate between values of $\beta$ in $y = e^{\beta x}$ functions.
    - Using a log scale should make it much easier to estimate $\beta$. We estimate slopes relatively accurately. (Mosteller et al. 1981)
    - Underestimation of exponential growth is common.
    - Numerical estimation is more accurate than graphical estimation for exponential curves 

### Functional Form

*How closley the function relates to an exponential (how about polynomial or logistic curves?)*

- @jones1977polynomial 

    - subjective extrapolation was best described by a low-order polynomial, and specifically the quartic collocation polynomial.
    
- @wagenaar_extrapolation_1978 

    - the exponential growth factor $\exp(b)$ is said to be underestimated as $\alpha\exp(\beta b)$.

- @jones_generalized_1979 

    - introduce a generalized polynomial model which proposes that subjects' extrapolations from exponential series consist of proportional functions of quadratic extrapolations.

### Order of Magnitude
*What are the min/max of the y-axis?*

- @siegler_numerical_2017 

    - whole number magnitude representations progress from a compressive, approximately logarithmic distribution to an approximately linear one. Transitions occur earlier for smaller than for larger ranges of whole numbers, corresponding both to the complexity of the numbers and to the ages when children gain experience with them. In summary, estimation proceeds logarithmically initially and transitions to linear later in development, for several different numerical ranges.

- @dehaeneLogLinearDistinct2008

    - in American children, logarithmic mapping does not disappear all at once, but vanishes first for small numbers and much later for larger numbers from 1 to 1000 (up to fourth or sixth grade in some children).

### Axis tick labels
*Scientific notation? Standard notation? Transition at a given value?*

- @friel_making_2001 

    - graph scale affects one's reading of the frequency of values.
    
- @fry1983theory and @rangecroft1991graphwork 

    - highlight the use of scale as as an important component of graph structure.

### Dotplots & Trend lines
- @wagenaar_extrapolation_1978 

    - the more data points, the worse the extrapolations. It was determined that extrapolation of exponential functions improves when less data points are shown.The willingness to produce large numbers, is affected when many data points are presented.
    
- @vanderplas_clusters_2017 

    - the addition trend lines emphasizes the “good continuation” of points in the plot. Consistent with the study's hypothesis, experimentation indicated that trend lines and prediction intervals, increase the probability of detecting the linear relationship.
    
- @cleveland1984many 

    - advocate smoothing of scatterplots to assist in detecting the shape of the point cloud in situations where the error in the data is substantial, or where the density of points changes along the abscissa.

### Estimation Scenario
- @friel_making_2001 

    - argue that researchers must consider the effect of the graph's visual characteristics (i.e., syntax) and the graph's context (i.semantics) on one's comprehension.

- @wagenaar1979pond 

    - use the representation of duckweed multiplying itself in a pond is as a research paradigm to study underestimation of exponential growth.

### References

