---
title: |
  Abstract: Eye Fitting Straight Lines in the Modern Era
type:
  - JSM 2021 Student Paper Competition (ASA sections on Statistical Computing and Statistical Graphics)
author:
  - name: Emily A. Robinson
    affil: a
    email: emily.robinson@huskers.unl.edu
  - name: Reka Howard
    affil: a
  - name: Susan VanderPlas
    affil: a
affiliation:
  - num: a
    address: |
      Department of Statistics, University of Nebraska - Lincoln,
bibliography: references.bib
output: 
  pdf_document:
    template: template-abstract.tex
    # template: template-abstract-blinded.tex
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F, eval = T, fig.path="./images/", fig.env="figure*")
```

How do statistical regression results compare to intuitive, visually fitted results? Fitting lines by eye through a set of points has been explored since the 20th century. Common methods of fitting trends by eye involve maneuvering a string, black thread, or ruler until the fit is suitable, then drawing the line through the set of points. In 2015, the New York Times introduced an interactive feature, called 'You Draw It', where readers are asked to input their own assumptions about various metrics and compare how these assumptions relate to reality. In this paper, we validate ‘You Draw It’ as a method for graphical testing, comparing results to the less technological method utilized in \citet{mosteller1981eye} and extending that study with formal statistical analysis methods. Results were consistent with those found in the previous study; when shown points following a linear trend, participants tended to fit the slope of the first principal component over the slope of the least-squares regression line. This trend was most prominent when shown data simulated with larger variances. This study reinforces the differences between intuitive visual model fitting and statistical model fitting, providing information about human perception as it relates to the use of statistical graphics.
