---
title: |
  Perception of exponentially increasing data displayed on a log scale
type:
  - JSM 2021 Student Paper Competition (ASA sections on Statistical Computing and Statistical Graphics)
author:
  - name: Emily A. Robinson
    affil: a
    email: emily.robinson@huskers.unl.edu
  - name: Reka Howard
    affil: a
  - name: Susan VanderPlas
    affil: a
affiliation:
  - num: a
    address: |
      Department of Statistics, University of Nebraska - Lincoln,
bibliography: references.bib
output: 
  pdf_document:
    template: template-abstract.tex
    include:
      # after_body: appendix.tex
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F, eval = T, fig.path="./images/", fig.env="figure*")
```

\
  Log scales are often used to display data over several orders of magnitude within one graph. During the COVID-19 pandemic, we have seen both the benefits and the pitfalls of using log scales to display case counts. 
In this paper, we explore the use of linear and log-transformed scales to determine whether our ability to notice differences in exponentially increasing trends is impacted by the scales choice.
We conducted a visual inference experiment in which participants were shown a series of lineup plots (consisting of 19 null panels and 1 target panel generated by differing model parameters) and asked to identify the panel that was most different from the others.
Our results indicated that when there were larger curvature difference, the choice of scale has no impact and participants accurately differentiated between the two curves on both the linear and log scale. 
However, we found that displaying exponentially increasing data on a log-transformed scale improved the accuracy of differentiating between trends with slight curvature differences, particularly when identifying an exponential curve with less curvature than others. 
An exception occured when identifying a plot with curvature embedded in surrounding plots closely relating to a linear trend, indicating that it is easy to identify a curve in a bunch of lines but much harder to identify a line in a bunch of curves.
