---
title: "Difficulty Exploration"
author: "Emily Robinson"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE, warning = F, message = F}
knitr::opts_chunk$set(echo = T, out.width = "100%", dpi = 300, message = F)
library(knitr)
require(tidyverse)
require(gridExtra)
require(scales)
library(purrr)
```

# Exponential (Multiplicative Errors)

For $$y_i = \alpha e^{(\beta x_i + \epsilon_i)} + \theta$$ 
with $\epsilon_i \sim N(0,\sigma^2)$
where $\theta = \frac{yMax - yMin\times e^{\beta (xMax - xMin)}}{1 - e^{\beta xMax}}$ and $\alpha=\frac{yMin - \theta}{e^{\beta xMin+\sigma^2/2}}$. The domain was set to be $x\in (0,20)$ with $N = 20.$

```{r functions, warning = F, message = F}
# Exponential
expSim <- function(beta, sigma, nReps = 1, N = 20, xRange = c(0,20), yRange = c(1,100)){
  theta <- (yRange[2]-yRange[1]*(exp(beta*(xRange[2]-xRange[1]))))/(1-exp(beta*xRange[2]+sigma^2/2))
  alpha <- (yRange[1]-theta)/(exp(beta*xRange[1]+sigma^2/2))
  
  vals <- seq(xRange[1], xRange[2], length.out = N*3/4)
  xvals <- sample(vals, (N-2), replace = T)
  xvals <- jitter(c(xRange[1],xvals,xRange[2]))
  
  expData <- tibble(x = rep(xvals, nReps),
                    y = alpha*exp(beta*x + rnorm(N*nReps,0,sigma)) + theta)
  return(expData)
}

# Evaluate Fit 
calcLOF <- 
  function(sim.data){
    lof.mod <- lm(y ~ as.factor(x), data = sim.data)
    lof <- anova(lof.mod) %>% 
      broom::tidy() %>%
      filter(term == "as.factor(x)") %>%
      select(statistic)
    return(lof)
  }
```

```{r ExpMultParms, cache = F, warning = F, message = F}
#Identify parameters
parmCombos <- data.frame(Curvature = c("Hard", "Hard", "Medium", "Medium", "Easy", "Easy"),
                         Variability = c("Low", "High", "Low", "High", "Low", "High"),
                         beta  = c(0.07, 0.07, 0.15, 0.15, 0.33, 0.33),
                         sigma = c(0.05, 0.09, 0.12, 0.2, 0.25, 0.35)
                         )
parmCombos %>% kable(format = "pandoc")
```

```{r ExpMultVisuals5, cache = F, fig.width = 8, fig.height = 5, warning = F, message = F}
simData5 <- parmCombos %>%
                  mutate(data = pmap(list(beta,sigma,nReps = 8),expSim)) %>%
                  unnest(data)

simData5 %>%
  mutate(Curvature = factor(Curvature, levels = c("Easy", "Medium", "Hard"))) %>%
  mutate(Variability = factor(Variability, levels = c("Low", "High"))) %>%
  ggplot(aes(x = x, y = y)) +
  geom_point(shape = 1) +
  theme_bw() +
  facet_grid(Variability~Curvature) +
  ggtitle("Linear Scale")

simData5 %>%
  mutate(Curvature = factor(Curvature, levels = c("Easy", "Medium", "Hard"))) %>%
  mutate(Variability = factor(Variability, levels = c("Low", "High"))) %>%
  ggplot(aes(x = x, y = y)) +
  geom_point(shape = 1) +
  theme_bw() +
  facet_grid(Variability~Curvature) +
  scale_y_continuous(trans = "log10") +
  ggtitle("Log Scale")
```

```{r ExpMultVisuals1, cache = F, echo = T, fig.width = 8, fig.height = 5, warning = F, message = F}
simData1 <- parmCombos %>%
                  mutate(data = pmap(list(beta,sigma,nReps = 1),expSim)) %>%
                  unnest(data)

simData1 %>%
  mutate(Curvature = factor(Curvature, levels = c("Easy", "Medium", "Hard"))) %>%
  mutate(Variability = factor(Variability, levels = c("Low", "High"))) %>%
  ggplot(aes(x = x, y = y)) +
  geom_point(shape = 1) +
  theme_bw() +
  facet_grid(Variability~Curvature) +
  ggtitle("Linear Scale")

simData1 %>%
  mutate(Curvature = factor(Curvature, levels = c("Easy", "Medium", "Hard"))) %>%
  mutate(Variability = factor(Variability, levels = c("Low", "High"))) %>%
  ggplot(aes(x = x, y = y)) +
  geom_point(shape = 1) +
  theme_bw() +
  facet_grid(Variability~Curvature) +
  scale_y_continuous(trans = "log10") +
  ggtitle("Log Scale")
```

```{r ExpMultLOF, cache = F, echo = T, fig.width = 8, fig.height = 4, warning = F, message = F}

lofData <- parmCombos %>%
                  expand_grid(replicate = seq(1,1000,1)) %>%
                  mutate(data = pmap(list(beta,sigma,nReps = 10),expSim)) %>%
                  mutate(lof = map(data, calcLOF)) %>%
                  unnest(lof)

# Compare Varability within Curvature
lofData %>%
  mutate(Curvature = factor(Curvature, levels = c("Easy", "Medium", "Hard"))) %>%
  mutate(Variability = factor(Variability, levels = c("Low", "High"))) %>%
  ggplot(aes(x = statistic, fill = Variability, color = Variability)) +
  geom_density(alpha = 0.7) +
  scale_fill_brewer(palette = "Paired") + 
  scale_color_brewer(palette = "Paired") + 
  theme_bw() +
  facet_wrap(~Curvature, scale = "free") + 
  ggtitle("Lack of Fit within Curvature Levels \n Exponential with Multiplicative Error")

# Compare Curvature within Varability
lofData %>%
  mutate(Curvature = factor(Curvature, levels = c("Easy", "Medium", "Hard"))) %>%
  mutate(Variability = factor(Variability, levels = c("Low", "High"))) %>%
  ggplot(aes(x = statistic, fill = Curvature, color = Curvature)) +
  geom_density(alpha = 0.7) +
  scale_fill_brewer(palette = "Paired") + 
  scale_color_brewer(palette = "Paired") + 
  theme_bw() +
  facet_wrap(~Variability, scale = "free") + 
  ggtitle("Lack of Fit within Variability Levels \n Exponential with Multiplicative Error")
```