---
title: "Datasets"
author: "Susan Vanderplas"
output: html_document
---

# Prices of Computer Components over time

Data source: https://jcmit.net/diskprice.htm

```{r setup, include = F}
library(tidyverse)
library(readxl)
library(gridExtra)
library(ggpubr)
library(rvest)
library(lubridate)

knitr::opts_chunk$set(echo = F, fig.width = 8, fig.height = 4, out.width = "100%", dpi = 300, message = F)
```

```{r data, include = F}
mem_path <- here::here("data", "mem-disk-price.xlsx")
if (!file.exists(mem_path)) download.file("https://jcmit.net/MemDiskPrice-xl95.xls", mem_path, mode = "wb")

cnames <- c("dec_date", "price_per_mb", "year", "md", "ref1", "ref2", "ref3", "size_kb", "price", "speed", "memtype")
ctype <- c(rep("numeric", 3), rep("text", 4), rep("numeric", 2), rep("text", 2), rep("skip", 3))
mem_data <- read_xls(mem_path, sheet = "MEMORY", skip = 4, col_names= cnames, col_types = ctype)

cnames <- c("obs", "dec_date", "old_hd_price_mb", "floppy_price_mb", "hd_price_mb", "year", "md", "ref1", "ref2", "sales", "manuf", "model", "size", "type", "speed", "rotate", "cache", "size_mb", "cost")
ctype <- c(rep("numeric", 5), "skip", "skip", "numeric", rep("text", 8), rep("numeric", 2), "text", "numeric", "numeric")
disk_data <- read_xls(mem_path, sheet = "DDRIVES", skip = 4, col_names= cnames, col_types = ctype)
disk_data2 <- pivot_longer(disk_data, old_hd_price_mb:hd_price_mb, names_to = "disk_type", values_to = "price_per_mb") %>%
  mutate(disk_type = str_remove(disk_type, "_price_mb"))

cnames <- c("dec_date", "price_per_mb", "year", "month", "ref", "sales", "manuf", "series", "nom_size", "model", "form_factor", "type", "store", "max_rw", "max_iops", "effective_size", "cost")
ctype <- c("skip", "numeric", "skip", rep("numeric", 2), rep("text", 2), "skip", rep("text", 10), rep("numeric", 2))
ssd_data <- read_xls(mem_path, sheet = "SSD", skip = 4, col_names= cnames, col_types = ctype)

```

```{r}
grid.arrange(
ggplot(mem_data, aes(x = dec_date, y = price_per_mb)) + geom_line() + ggtitle("Computer Memory (RAM)"),
ggplot(mem_data, aes(x = dec_date, y = price_per_mb)) + geom_line() + scale_y_log10() + ggtitle("Computer Memory (RAM)"),
nrow = 1
)
```

```{r, message = F, warning = F}

combine_plots <- function(p1, p2) {
  legend <- get_legend(p1 + theme(legend.position = "bottom")) %>% as_ggplot()
  p1a <- p1 + theme(legend.position = "none")
  p2a <- p2 + theme(legend.position = "none")
  grid.arrange(p1a, p2a, legend, layout_matrix = matrix(c(1, 2, 1, 2, 1, 2, 1, 2, 3, 3), nrow = 5, byrow = T))
}

p1 <- ggplot(disk_data2, aes(x = dec_date, y = price_per_mb, color = disk_type)) + geom_line() + ggtitle("Disk Drives") + theme(legend.position = "bottom")
p2 <- ggplot(disk_data2, aes(x = dec_date, y = price_per_mb, color = disk_type)) + geom_line() + scale_y_log10() + ggtitle("Disk Drives") + guides(color = F)

combine_plots(p1, p2)
```

```{r}
grid.arrange(
ggplot(ssd_data, aes(x = dec_date, y = price_per_mb)) + geom_line() + ggtitle("Solid State Drive Storage"),
ggplot(ssd_data, aes(x = dec_date, y = price_per_mb)) + geom_line() + scale_y_log10() + ggtitle("Solid State Drive Storage"),
nrow = 1
)
```

# Cost for computational power over time

https://en.wikipedia.org/wiki/FLOPS#Hardware_costs

```{r, include = F}
fix_tbl_nums <- function(x) {
  str_replace(x, " billion", "e9") %>%
    str_replace(" trillion", "e12") %>%
           str_remove_all("[$,]")
}

gflop_cost <- read_html("https://en.wikipedia.org/wiki/FLOPS#Hardware_costs") %>%
  html_table(fill = T) %>%
  `[[`(4) %>%
  set_names(c("Date", "cost_gflops", "cost_gflops_2019", "cost_tflops_2017", "platform", "comments")) %>%
  mutate(Date = ifelse(str_sub(Date, 1, 1) == 1, paste("January", Date), Date) %>%
           paste("1", .) %>%
           lubridate::dmy()
         ) %>%
  # This requires the latest version of dplyr... 
  mutate(across(matches("cost"), fix_tbl_nums)) %>%
  mutate(across(matches("cost"), as.numeric))
```

```{r}
grid.arrange(
ggplot(gflop_cost, aes(x = Date, y = cost_gflops)) + geom_point() + geom_line() + ggtitle("Cost of Computational Power") + ylab("$/GFLOPS"),
ggplot(gflop_cost, aes(x = Date, y = cost_gflops)) + geom_point() + geom_line() + scale_y_log10() + ggtitle("Cost of Computational Power") + ylab("$/GFLOPS"),
nrow = 1
)

grid.arrange(
ggplot(filter(gflop_cost, decimal_date(Date) > 2000), aes(x = Date, y = cost_gflops)) + geom_point() + geom_line() + ggtitle("Cost of Computational Power") + ylab("$/GFLOPS"),
ggplot(filter(gflop_cost, decimal_date(Date) > 2000), aes(x = Date, y = cost_gflops)) + geom_point() + geom_line() + scale_y_log10() + ggtitle("Cost of Computational Power") + ylab("$/GFLOPS"),
nrow = 1
)
```


# Computing Power
Data from https://www.top500.org/lists/

```{r}
url <- "https://www.top500.org/lists/"
data_file <- here::here("data/supercomputers.Rdata")
if (!file.exists(data_file)) {
  get_table_dat <- function(url2) {
    tmp <- read_html(url2) %>%
      html_table() %>%
      unlist(recursive = F) %>%
      as_tibble() %>%
      set_names(
        names(.) %>%
          str_to_lower() %>%
          str_replace_all("[ [:punct:]]{1,}", " ") %>%
          str_trim() %>%
          str_replace_all(" ", "_") 
      )
      # set_names(c("rank", "site", "system", "cores", "rmax_tflops_s", "rpeak_tflops_s", "power_kw"))
    
    tmp %>% 
      mutate(across(matches("cores|rmax|rpeak|power"), ~(if(is.character(.)) {parse_number(.)} else {.})))
  }
  
  list_links <- read_html(url) %>%
    xml_nodes("#squarelist li a") %>%
    purrr::map_df(., ~tibble(link = xml_attr(., "href"), date = str_replace(link, ".*(\\d{4})/(\\d{2})", "\\1 \\2 01") %>% ymd())) %>%
    mutate(link = str_replace(link, "lists", "list") %>%
             paste("https://www.top500.org", ., sep = "")) %>%
    mutate(data = purrr::map(link, get_table_dat))
  
  computing_power <- list_links %>%
    select(date, data) %>%
    unnest(data) %>%
    mutate(rank = factor(rank, ordered = T)) %>%
    mutate(rmax_tflop_s = ifelse(is.na(rmax_tflop_s), rmax_gflop_s / 1000, rmax_tflop_s),
           rpeak_tflop_s = ifelse(is.na(rpeak_tflop_s), rpeak_gflop_s / 1000, rpeak_tflop_s))
  
  save(list_links, computing_power, file = data_file)
}
load(data_file)
```

```{r}
combine_plots(
computing_power %>%
  filter(rank <= 3) %>%
  ggplot(aes(x = date, y = cores, color = rank)) + geom_line() + theme(axis.title.x = element_blank()) + 
  ggtitle("Cores in Top 3 Supercomputers"),

computing_power %>%
  filter(rank <= 3) %>%
  ggplot(aes(x = date, y = cores, color = rank)) + geom_line() + scale_y_log10() + theme(axis.title.x = element_blank()) + 
  ggtitle("Cores in Top 3 Supercomputers")
)

```

```{r}
combine_plots(
computing_power %>%
  filter(rank <= 3) %>%
  ggplot(aes(x = date, y = rmax_tflop_s, color = rank)) + geom_line() + theme(axis.title.x = element_blank()) + 
  ggtitle("Max Performance in Top 3 Supercomputers")
,
computing_power %>%
  filter(rank <= 3) %>%
  ggplot(aes(x = date, y = rmax_tflop_s, color = rank)) + geom_line() + theme(axis.title.x = element_blank()) + scale_y_log10() + 
  ggtitle("Max Performance in Top 3 Supercomputers")
)

```

```{r}
combine_plots(
computing_power %>%
  filter(rank <= 3) %>%
  ggplot(aes(x = date, y = rpeak_tflop_s, color = rank)) + geom_line() + theme(axis.title.x = element_blank()) + 
  ggtitle("Theoretical Peak Performance\n in Top 3 Supercomputers")
,
computing_power %>%
  filter(rank <= 3) %>%
  ggplot(aes(x = date, y = rpeak_tflop_s, color = rank)) + geom_line() + theme(axis.title.x = element_blank()) + scale_y_log10() + 
  ggtitle("Theoretical Peak Performance\n in Top 3 Supercomputers")
)
```
