---
title: "Difficulty Exploration"
author: "Emily Robinson"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, out.width = "100%", dpi = 300, message = F)
library(knitr)
require(tidyverse)
require(gridExtra)
require(scales)
library(purrr)

# Exponential ---------------------------------------------------------------------------------------
simulate.exponential <- 
  function(N, xRange = c(1,N), nReps, beta, muErr, sdErr, errorType, ...){
    
    exp.data <- data.frame(x = rep(seq(xRange[1], xRange[2], length.out = N), nReps), y = NA)
    
    theta <- 0
    
    if(errorType %in% c("Mult", "mult", "Multiplicative", "multiplicative")){
      # alpha <- sqrt(1/(exp(2*sdErr^2)-exp(sdErr^2)))
      alpha <- 1/(exp((sdErr^2)/2))
      exp.data$y <- alpha*exp(beta*exp.data$x + rnorm(N*nReps, muErr, sdErr)) + theta
    } else { 
      alpha <- 1
      if(errorType %in% c("Add", "add", "Additive", "additive")){
        exp.data$y <- alpha*exp(beta*exp.data$x) + theta + rnorm(N*nReps, muErr, sdErr)
      }
    }
    
    return(exp.data)
  }

# Quadratic ------------------------------------------------------------------------

simulate.quadratic <- 
  function(N, nReps, xRange = c(1,N), beta0, beta1, beta2, muErr, sdErr, ...){
    
    quad.data <- data.frame(x = rep(seq(xRange[1], xRange[2], length.out = N), nReps), y = NA)
    quad.data$y <- beta0 + beta1*quad.data$x + beta2*quad.data$x^2 + rnorm(N*nReps, muErr, sdErr)
    
    return(quad.data)
  }

# Overall Simulation Function ----------------------------------------------------------------

simulate.data <- 
  function(simulateFunction, ...){
    sim.data <- simulateFunction(...)
  }

# Evaluate Fit ---------------------------------------------------------------------

calcLOF <- 
  function(sim.data){
    if(nrow(sim.data)/length(unique(sim.data$x)) > 1){
    lof.mod <- lm(y ~ as.factor(x), data = sim.data)
    lof <- anova(lof.mod) %>% 
      broom::tidy() %>%
      filter(term == "as.factor(x)") %>%
      select(statistic)
    } else {
      lof.mod <- NULL
      lof <- NULL
    }
    return(lof)
  }
```

*See https://emily-robinson.shinyapps.io/SimulationExplorationApp_v2/ to look at other parameter combinations.*

# Exponential: Multiplicative

For $$y = \alpha e^{(\beta x + \epsilon)}$$ 
with $\epsilon \sim N(0,\sigma)$

where

\begin{align*}
xRange &= (0, 20)\\
N &= 20\\
\alpha & = \frac{1}{e^{\sigma^2/2}}\\
\end{align*}

*See [alpha-calculation.pdf](https://github.com/srvanderplas/Perception-of-Log-Scales/blob/master/documentation/alpha-calculation.pdf) for* $\alpha$ *calculations.*

```{r ExpMultParms, cache = F, echo = F}
#Identify parameters
parmCombos <- data.frame(Curvature = c("Hard", "Hard", "Medium", "Medium", "Easy", "Easy"),
                         Variability = c("Low", "High", "Low", "High", "Low", "High"),
                         beta  = c(0.07, 0.07, 0.15, 0.15, 0.3, 0.3),
                         sdErr = c(0.05, 0.07, 0.12, 0.18, 0.3, 0.5)
                         )
parmCombos %>% kable(format = "pandoc")
```

```{r ExpMultVisuals5, cache = F, echo = F, fig.width = 6, fig.height = 6}
sim.data.all <- data.frame("x" = NA, "y" = NA, "Curvature" = NA, "Variability" = NA)
for(k in 1:nrow(parmCombos)){
  sim.data.new <- simulate.data(simulateFunction = simulate.exponential, 
                                N = 20, 
                                nReps = 5,
                                xRange = c(1,20), 
                                
                                # Exponential Parameters
                                alpha = 1,
                                beta = parmCombos[k, "beta"], 
                                theta = 0,
                                
                                # Quadratic Parameters
                                beta0 = 0,
                                beta1 = 0, 
                                beta2 = 0.01,
                                
                                muErr = 0, 
                                sdErr = parmCombos[k, "sdErr"],
                                errorType = "mult")
  sim.data.new$Curvature <- parmCombos[k, "Curvature"]
  sim.data.new$Variability <- parmCombos[k, "Variability"]
  sim.data.all <- rbind(sim.data.all, sim.data.new)
}

sim.data.all[-1,] %>%
  mutate(Curvature = factor(Curvature, levels = c("Easy", "Medium", "Hard"))) %>%
  mutate(Variability = factor(Variability, levels = c("Low", "High"))) %>%
  ggplot(aes(x = x, y = y)) +
  geom_point(shape = 1) +
  theme_bw() +
  facet_grid(Curvature ~ Variability, scale = "free_y")
```

```{r ExpMultVisuals1, cache = F, echo = F, fig.width = 6, fig.height = 6}
sim.data.all <- data.frame("x" = NA, "y" = NA, "Curvature" = NA, "Variability" = NA)
for(k in 1:nrow(parmCombos)){
  sim.data.new <- simulate.data(simulateFunction = simulate.exponential, 
                                N = 20, 
                                nReps = 1,
                                xRange = c(1,20), 
                                
                                # Exponential Parameters
                                alpha = 1,
                                beta = parmCombos[k, "beta"], 
                                theta = 0,
                                
                                # Quadratic Parameters
                                beta0 = 0,
                                beta1 = 0, 
                                beta2 = 0.01,
                                
                                muErr = 0, 
                                sdErr = parmCombos[k, "sdErr"],
                                errorType = "mult")
  sim.data.new$Curvature <- parmCombos[k, "Curvature"]
  sim.data.new$Variability <- parmCombos[k, "Variability"]
  sim.data.all <- rbind(sim.data.all, sim.data.new)
}

sim.data.all[-1,] %>%
  mutate(Curvature = factor(Curvature, levels = c("Easy", "Medium", "Hard"))) %>%
  mutate(Variability = factor(Variability, levels = c("Low", "High"))) %>%
  ggplot(aes(x = x, y = y)) +
  geom_point(shape = 1) +
  theme_bw() +
  facet_grid(Curvature ~ Variability, scale = "free_y")
```

```{r ExpMultLOF, cache = F, echo = F, fig.width = 8, fig.height = 4}
lofStats <- data.frame("LOF" = NA, "Curvature" = NA, "Variability" = NA)
for(k in 1:nrow(parmCombos)){
  sim.data_0.1 <- replicate(n = 1000,
                            simulate.data(simulateFunction = simulate.exponential, 
                                          N = 20, 
                                          nReps = 10,
                                          xRange = c(1,20), 
                                          
                                          # Exponential Parameters
                                          alpha = 1,
                                          beta = parmCombos[k, "beta"], 
                                          theta = 0,
                                          
                                          # Quadratic Parameters
                                          beta0 = 0,
                                          beta1 = 0, 
                                          beta2 = 0.01,
                                          
                                          muErr = 0, 
                                          sdErr = parmCombos[k, "sdErr"],
                                          errorType = "mult"), 
                            simplify = FALSE)
  lofStats.new <- map(sim.data_0.1, calcLOF) %>% unlist() %>% as.matrix() %>% as.data.frame()
  colnames(lofStats.new) <- c("LOF")
  lofStats.new$Curvature <- parmCombos[k, "Curvature"]
  lofStats.new$Variability <- parmCombos[k, "Variability"]
  lofStats <- rbind(lofStats, lofStats.new)
}

# Compare Varability within Curvature
lofStats[-1,] %>%
  mutate(Curvature = factor(Curvature, levels = c("Easy", "Medium", "Hard"))) %>%
  mutate(Variability = factor(Variability, levels = c("Low", "High"))) %>%
  ggplot(aes(x = LOF, fill = Variability, color = Variability)) +
  geom_density(alpha = 0.7) +
  scale_fill_brewer(palette = "Paired") + 
  scale_color_brewer(palette = "Paired") + 
  theme_bw() +
  facet_wrap(~Curvature, scale = "free") + 
  ggtitle("Lack of Fit by Difficulty Level \n Exponential with Multiplicative Error")

# Compare Curvature within Varability
lofStats[-1,] %>%
  mutate(Curvature = factor(Curvature, levels = c("Easy", "Medium", "Hard"))) %>%
  mutate(Variability = factor(Variability, levels = c("Low", "High"))) %>%
  ggplot(aes(x = LOF, fill = Curvature, color = Curvature)) +
  geom_density(alpha = 0.7) +
  scale_fill_brewer(palette = "Paired") + 
  scale_color_brewer(palette = "Paired") + 
  theme_bw() +
  facet_wrap(~Variability, scale = "free") + 
  ggtitle("Lack of Fit by Difficulty Level \n Exponential with Multiplicative Error")
```


